[tools]
rojo = {github = "rojo-rbx/rojo", version = "7.*"}
wally = {github = "upliftgames/wally", version = "0.*"}
stylua = {github = "JohnnyMorganz/StyLua", version = "0.*"}
selene = {github = "Kampfkarren/selene", version = "0.*"}