[package]
name = "metop/collecting-adventure"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.3"
signal = "sleitnick/signal@2.0.1"
roact = "roblox/roact@1.4.4"
promise = "evaera/promise@4.0.0"